In [1]:
import numpy as np
from numpy import pi
from numpy import newaxis

In [2]:
#Defining numpy arrays

arr1 = np.array([], dtype="int8")    #Empty array
#Changed data type to 8-bit integer here, default was 64-bit float (float64); specifying dtype can help save space

arr2 = np.array([1, 4, 9])    #1-D array

arr3 = np.array([[1, 2, 3], [1, 4, 9], [1, 8, 27]])    #2-D array

arr4 = np.array([ [[1, 2, 3]], [["a", "b", "c"]] ])    #3-D array 

arr5 = np.arange(4, 19, 2).reshape (2, 4)    #for i=4; i<19; i+2

arr6 = np.linspace(5, 9.5, 10).reshape(5, 2)    #Creates an array starting from 5, ending at 9.5 (included), having 10 elements

#Creating them can give a warning when the shape isn't consistent

In [3]:
print (arr1)
print ("Shape:", arr1.shape, ", Dimension:", arr1.ndim, ", Data Type:", arr1.dtype)
print ("Size of items (bytes):", arr1.itemsize, ", No. of items:", arr1.size, ", Total size (bytes):", arr1.itemsize*arr1.size)
#arr1.itemsize * arr1.size = arr1.nbytes (number of bytes taken up by arr1) 
print()

print (arr2)
print ("Shape:", arr2.shape, ", Dimension:", arr2.ndim, ", Data Type:", arr2.dtype)
print ("Size of items (bytes):", arr2.itemsize, ", No. of items:", arr2.size, ", Total size (bytes):", arr2.itemsize*arr2.size)
print()

print (arr3)
print ("Shape:", arr3.shape, ", Dimension:", arr3.ndim,", Data Type:", arr3.dtype)
print ("Size of items (bytes):", arr3.itemsize, ", No. of items:", arr3.size, ", Total size (bytes):", arr3.itemsize*arr3.size)
print ()

print (arr4)
print ("Shape:", arr4.shape, ", Dimension:", arr4.ndim, ", Data Type:", arr4.dtype)
#Gives <U11 (a string dtype of length<=11; as strings can't be turned into numbers, they make everything else strings to match)
print ("Size of items (bytes):", arr4.itemsize, ", No. of items:", arr4.size, ", Total size (bytes):", arr4.itemsize*arr4.size)
print ()

print (arr5)
print ("Shape:", arr5.shape, ", Dimension:", arr5.ndim, ", Data Type:", arr5.dtype)
#Gives <U11 (a string dtype of length<=11; as strings can't be turned into numbers, they make everything else strings to match)
print ("Size of items (bytes):", arr5.itemsize, ", No. of items:", arr5.size, ", Total size (bytes):", arr5.itemsize*arr5.size)
print ()

print (arr6)
print ("Shape:", arr6.shape, ", Dimension:", arr6.ndim, ", Data Type:", arr6.dtype)
#Gives <U11 (a string dtype of length<=11; as strings can't be turned into numbers, they make everything else strings to match)
print ("Size of items (bytes):", arr6.itemsize, ", No. of items:", arr6.size, ", Total size (bytes):", arr6.itemsize*arr6.size)

#Shape (2, 1, 3) where 2 = No. of 2-ary brackets, 1 = No. of 3-ary brackets, 3 = No. of elements within innermost brackets

[]
Shape: (0,) , Dimension: 1 , Data Type: int8
Size of items (bytes): 1 , No. of items: 0 , Total size (bytes): 0

[1 4 9]
Shape: (3,) , Dimension: 1 , Data Type: int32
Size of items (bytes): 4 , No. of items: 3 , Total size (bytes): 12

[[ 1  2  3]
 [ 1  4  9]
 [ 1  8 27]]
Shape: (3, 3) , Dimension: 2 , Data Type: int32
Size of items (bytes): 4 , No. of items: 9 , Total size (bytes): 36

[[['1' '2' '3']]

 [['a' 'b' 'c']]]
Shape: (2, 1, 3) , Dimension: 3 , Data Type: <U11
Size of items (bytes): 44 , No. of items: 6 , Total size (bytes): 264

[[ 4  6  8 10]
 [12 14 16 18]]
Shape: (2, 4) , Dimension: 2 , Data Type: int32
Size of items (bytes): 4 , No. of items: 8 , Total size (bytes): 32

[[5.  5.5]
 [6.  6.5]
 [7.  7.5]
 [8.  8.5]
 [9.  9.5]]
Shape: (5, 2) , Dimension: 2 , Data Type: float64
Size of items (bytes): 8 , No. of items: 10 , Total size (bytes): 80


In [4]:
array1 = np.arange(1, 10).reshape([3, 3])
print (array1, array1.shape)
print()

array2 = np.arange(5, 8).reshape([3, 1])
print (array2, array2.shape)
print()

array3 = np.arange(11, 14).reshape([1, 3])    #Reshaping just added an extra set of [] brackets
print (array3, array3.shape)
print()

print (array2.ravel(), array2.ravel().shape)    #Ravel turned it into a 1-D array without changing the original variable

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)

[[5]
 [6]
 [7]] (3, 1)

[[11 12 13]] (1, 3)

[5 6 7] (3,)


In [5]:
#Sum

print (np.sum(array1, axis = 0))
#1+4+7 2+5+8 3+6+9    (Collapsed 3 rows into 1 by making each column = its total)

print (np.sum(array1, axis = 1))
#1+2+3 4+5+6 7+8+9    (Collapsed 3 columns into 1 by making each row = its total, but still displayed like a row matrix)

print (np.sum(array1))
#Sums up all the elements

[12 15 18]
[ 6 15 24]
45


In [6]:
#Concatenate

print (np.concatenate([array1, array2], axis=1))
print (np.concatenate([array1, array2], axis=1).shape)
#Accepted axis=1 (along columns) as both have same number of rows (added a column having equal number of rows)

print ()
print (np.concatenate([array1, array3], axis=0))
print (np.concatenate([array1, array3], axis=0).shape)
#Accepted axis=0 (along rows) as both have same number of columns (added a row having equal number of columns)

#With 1-D arrays
a1 = np.array([2, 4, 5])
a2 = np.array([3, 6, 7, 9])

print()
print (np.concatenate([a1, a2]))            #Since the arrays are both 1-D, their unequal number of elements doesn't matter.
print (np.concatenate([a1, a2], axis=0))    #Specifying the axis doesn't do anything here as there's only 1 axis anyway.
print (np.concatenate([a1, a2]).shape)      #Just returns the number of elements for a 1-D array

[[1 2 3 5]
 [4 5 6 6]
 [7 8 9 7]]
(3, 4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]]
(4, 3)

[2 4 5 3 6 7 9]
[2 4 5 3 6 7 9]
(7,)


In [7]:
#Element-wise operations

print (arr3)
print (arr3.data)
print()

print (arr3+3)
print (arr3-3)
print (arr3/3)
print (arr3*3)
print()

print (np.exp(arr3))
print (np.sin(arr3))
print (np.cos(arr3))
print (np.tan(arr3))
print (np.sin(arr3)/np.cos(arr3) == np.tan(arr3))

[[ 1  2  3]
 [ 1  4  9]
 [ 1  8 27]]

[[ 4  5  6]
 [ 4  7 12]
 [ 4 11 30]]
[[-2 -1  0]
 [-2  1  6]
 [-2  5 24]]
[[0.33333333 0.66666667 1.        ]
 [0.33333333 1.33333333 3.        ]
 [0.33333333 2.66666667 9.        ]]
[[ 3  6  9]
 [ 3 12 27]
 [ 3 24 81]]

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [2.71828183e+00 5.45981500e+01 8.10308393e+03]
 [2.71828183e+00 2.98095799e+03 5.32048241e+11]]
[[ 0.84147098  0.90929743  0.14112001]
 [ 0.84147098 -0.7568025   0.41211849]
 [ 0.84147098  0.98935825  0.95637593]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [ 0.54030231 -0.65364362 -0.91113026]
 [ 0.54030231 -0.14550003 -0.29213881]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.55740772  1.15782128 -0.45231566]
 [ 1.55740772 -6.79971146 -3.2737038 ]]
[[False  True  True]
 [False False False]
 [False False False]]


In [8]:
#Multiplication of matrices

print (arr3)
print (array1)
print (arr3 * array1)
#This only multiplies the respective elements, not how we do in mathematics

#In the mathematical one, we need number of columns in first matrix = number of rows in second matrix
print (np.matmul(array1, arr3))
print (np.matmul(arr3, array1))

[[ 1  2  3]
 [ 1  4  9]
 [ 1  8 27]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[  1   4   9]
 [  4  20  54]
 [  7  64 243]]
[[  6  34 102]
 [ 15  76 219]
 [ 24 118 336]]
[[ 30  36  42]
 [ 80  94 108]
 [222 258 294]]


In [9]:
#Accessing/Changing specific elements/rows/columns
array0 = np.arange(1, 10).reshape([3, 3])
print ("Initial:")
print (array0)
print()

array0[1] = [1, 6, 0]        #Changing specific row (Doesn't need the columns = : to be specified)
array0[0, :] = 6             #Makes all the elements of that row/column = value passed
array0[:, 2] = [4, 5, 10]    #Changing specific column (With columns, we need the rows to be specified)
array0[0, 0] = 11            #Changing specific element
print ("Final:")
print (array0)
print()

print (array0[2])            #Accessing specific row
print (array0[2, :])         #Another way of accessing specific row
print (array0[2, 0:3:1])     #Yet another way of accessing specific row
#With numpy arrays, too, the indices can be negative

print()
print (array0[:, 2])         #Accessing specific column
print (array0[0:3:1, 2])     #Yet another way of accessing specific row
#It means for column 3 (index 2), start at row index 0 till row index 2 (stop before 3) and move at a step size of 1

print()
print (array0[2, 1])    #Accessing specific element
print (array0[1, 0])
#Needless to say, this is all possible (but a little more complex) with arrays having more dimensions.

Initial:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Final:
[[11  6  4]
 [ 1  6  5]
 [ 7  8 10]]

[ 7  8 10]
[ 7  8 10]
[ 7  8 10]

[ 4  5 10]
[ 4  5 10]

8
1


In [10]:
#Initialising some special matrices

s1 = np.zeros(5)    #Initialises all elements as 0.0 or 0. (float 64 unless specified otherwise)
print (s1)
print ()

s2 = np.ones((4, 5))    #Initialises all elements as 1.0 or 1. (float 64 unless specified otherwise)
print (s2)
print()

s3 = np.full((3, 2, 4), "Hi")    #Initialises all elements as the value passed 
print (s3)
print()

s4 = np.full_like(array0, "ITT", dtype="U3")    
#Initialises all elements as value passed (data type must be the same/specified differently), and size as that of array passed
print (s4)
print()

s5 = np.random.rand(3, 4, 1)    #Initialises elements as random decimal numbers between 0 and 1 (can change after every run)
print (s5)
s6 = np.random.rand()           #Passing no size arguments will return a random decimal number
print (s6)
print()

s7 = np.random.random_sample(array0.shape)    #Initialises elements as random float numbers (0 to 1), takes the specified shape
#Accepts only 1 argument, so it can either be an integer or a function (returning an integer)
print (s7)
print()

s8 = np.random.randint(0, 10, size=(4, 4))    #size could also have been specified as the shape of another array
#Initialises elements as random integers in the specified range (can change after every run)
print (s8)
s9 = np.random.randint(-10, -8)           
#Must pass at least 2 arguments (lower and upper limits (upper excluded)), size not specified implies one value
print (s9)
s15 = np.random.default_rng((6, 2))    #Can have 1 or no argument, should be positional (can be (3, 4, 5) etc.)
print (s15)
s16 = np.empty((4, 2))    #Creates an array whose initial content is random
print (s16)
s17 = np.empty_like(array2)    #Works like full_like and the data type can be specified here too
print (s17)
print()

s10 = np.identity(0)    #Creates an identity matrix (a square matrix with diagonal elements=1, rest 0)
s11 = np.identity(1)
s12 = np.identity(2)
print (s10)
print (s11)
print (s12)
print()

s13 = np.repeat (array3, 5, axis=0)    #Creates a matrix made by repeating the passed matrix the specified number of times
s14 = np.repeat (array3, 4, axis=1)    #axis = 1 by default here
print (s13)
print (s14)

#Typically, matrices choose int32, float64 or U2 as the default data types

[0. 0. 0. 0. 0.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[['Hi' 'Hi' 'Hi' 'Hi']
  ['Hi' 'Hi' 'Hi' 'Hi']]

 [['Hi' 'Hi' 'Hi' 'Hi']
  ['Hi' 'Hi' 'Hi' 'Hi']]

 [['Hi' 'Hi' 'Hi' 'Hi']
  ['Hi' 'Hi' 'Hi' 'Hi']]]

[['ITT' 'ITT' 'ITT']
 ['ITT' 'ITT' 'ITT']
 ['ITT' 'ITT' 'ITT']]

[[[0.9861397 ]
  [0.24121805]
  [0.60634509]
  [0.03606827]]

 [[0.92848489]
  [0.53398675]
  [0.80366739]
  [0.24249688]]

 [[0.31297321]
  [0.41825154]
  [0.80733575]
  [0.02500379]]]
0.7380582256531919

[[0.51120667 0.61265229 0.02580368]
 [0.82607976 0.48947814 0.01639084]
 [0.66246343 0.59696417 0.21902459]]

[[7 9 8 8]
 [7 3 8 9]
 [1 9 0 3]
 [0 5 5 5]]
-10
Generator(PCG64)
[[0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000]
 [0.000e+000 6.087e-321]
 [1.000e+000 8.000e+000]]
[[16843009]
 [16843009]
 [16843009]]

[]
[[1.]]
[[1. 0.]
 [0. 1.]]

[[11 12 13]
 [11 12 13]
 [11 12 13]
 [11 12 13]
 [11 12 13]]
[[11 11 11 11 12 12 12 12 13 13 13 13]]


In [11]:
#Determinant of a matrix (returned as a float64 type value by default)
print (np.linalg.det(arr3))
print (np.linalg.det(array1))
print (np.linalg.det(np.zeros((2, 2))))    #Bound to be 0
print (np.linalg.det(np.identity(5)))      #Bound to be 1

12.0
0.0
0.0
1.0


In [12]:
#Other functions
print (np.linalg.inv(arr3))
print (np.linalg.inv(np.identity(5)))          #Identity matrices are inverses of themselves
print ()

print (np.matrix.transpose(arr3))
print (arr3.T)                                 #Another way to get the transpose
print (np.matrix.transpose(np.identity(5)))    #Identity matrices are transposes of themselves
print (np.identity(5).T)
print()

print (np.floor(arr3))    #Rounds off to the previous (smaller) integer (like -1.2 to -2 and 0.2 to 0)
nr, nc = array1.shape     #A way to get the number of rows and the number of columns in an array
print (nr, nc)

[[ 3.         -2.5         0.5       ]
 [-1.5         2.         -0.5       ]
 [ 0.33333333 -0.5         0.16666667]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[ 1  1  1]
 [ 2  4  8]
 [ 3  9 27]]
[[ 1  1  1]
 [ 2  4  8]
 [ 3  9 27]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[ 1.  2.  3.]
 [ 1.  4.  9.]
 [ 1.  8. 27.]]
3 3


In [13]:
#Stacking arrays

print (arr2)
arr7 = arr3.ravel()
print (arr7)
print()

print (np.hstack((arr2, arr7)))    #vstack wouldn't have worked for these arrays since their numbers of columns are different
print (np.hstack((arr7, arr2)))
print()

arr7 = arr7.reshape(3, 3)
print (np.vstack((arr2, arr7)))
print (np.vstack((arr7, arr2)))

[1 4 9]
[ 1  2  3  1  4  9  1  8 27]

[ 1  4  9  1  2  3  1  4  9  1  8 27]
[ 1  2  3  1  4  9  1  8 27  1  4  9]

[[ 1  4  9]
 [ 1  2  3]
 [ 1  4  9]
 [ 1  8 27]]
[[ 1  2  3]
 [ 1  4  9]
 [ 1  8 27]
 [ 1  4  9]]


In [14]:
#Splitting an array

print (arr7)
print (np.hsplit(arr7, 3))    #Creates equally-sized vertical matrices by separating the columns
print (np.vsplit(arr7, 3))    #Creates equally-sized horizontal matrices by separating the rows

[[ 1  2  3]
 [ 1  4  9]
 [ 1  8 27]]
[array([[1],
       [1],
       [1]]), array([[2],
       [4],
       [8]]), array([[ 3],
       [ 9],
       [27]])]
[array([[1, 2, 3]]), array([[1, 4, 9]]), array([[ 1,  8, 27]])]


In [15]:
#Statistics

ar1= np.array([[6, 5, 4], [7, 8, 9]])
print (ar1)
print()

print (np.min(ar1))            #Smallest element
print (np.min(ar1, axis=0))    #Smallest elements from each row
print (np.min(ar1, axis=1))    #Smallest elements from each column
print()

print (np.max(ar1))            #Largest element
print (np.max(ar1, axis=0))    #Largest elements from each row
print (np.max(ar1, axis=1))    #Largest elements from each column
print()

print (np.mean(ar1))             #Mean across the whole matrix
print (np.average(ar1))          #Mean and average give the same result
print (np.mean(ar1, axis =0))    #Mean across columns
print (np.mean(ar1, axis =1))    #Mean across rows
print ()

print (np.median(ar1))             #Median across the whole matrix
print (np.median(ar1, axis =0))    #Median across columns
print (np.median(ar1, axis =1))    #Mean across rows
print ()                           #Median was the same as mean in this case

print (np.std(ar1))             #Standard Deviation across the whole matrix
print (np.std(ar1, axis =0))    #Standard Deviation across columns
print (np.std(ar1, axis =1))    #Standard Deviation across rows
print () 

print (np.var(ar1))             #Variance across the whole matrix
print (np.var(ar1, axis =0))    #Variance across columns
print (np.var(ar1, axis =1))    #Variance across rows
print ()                        #Variance = (Standard Deviation)^2

[[6 5 4]
 [7 8 9]]

4
[6 5 4]
[4 7]

9
[7 8 9]
[6 9]

6.5
6.5
[6.5 6.5 6.5]
[5. 8.]

6.5
[6.5 6.5 6.5]
[5. 8.]

1.707825127659933
[0.5 1.5 2.5]
[0.81649658 0.81649658]

2.9166666666666665
[0.25 2.25 6.25]
[0.66666667 0.66666667]



In [16]:
#Boolean Indexing
ar2 = np.array([[4, 5, 2], [7, 6, 9], [3, 1, 8], [0, 12, 19]])
print (ar2, ar2.shape)
print()

ar3 = ar2>6
print (ar3)
print (ar2[ar3])       #Returns elements that return True in ar3
print (ar2[ar2<=6])    #Will return the elements of ar2 other than the ones received by the above command
print (ar3.any())      #If there are any true values in ar3
print (ar3.all())      #If all values in ar3 are True
print()

#Multiple Indexing (explains why the above works)
print (ar2[[3, 2]])    #Fetches the specified indices (which point to rows in this case)
#print (ar2[1[1], 0[0]]) to fetch the specified elements didn't work
print()

#Automatic reshaping (done by passing the unknown value as -1)
ar4 = ar2.reshape(2, -1)
print (ar4, ar4.shape)

[[ 4  5  2]
 [ 7  6  9]
 [ 3  1  8]
 [ 0 12 19]] (4, 3)

[[False False False]
 [ True False  True]
 [False False  True]
 [False  True  True]]
[ 7  9  8 12 19]
[4 5 2 6 3 1 0]
True
False

[[ 0 12 19]
 [ 3  1  8]]

[[ 4  5  2  7  6  9]
 [ 3  1  8  0 12 19]] (2, 6)


In [17]:
#Reading a file from the system

file1 = np.genfromtxt("Numpy_Test1.txt", delimiter=",")    #Reads the txt file and recognises the specified delimiter
print (file1)
file2 = file1.astype("int8")    #Changes the data type
print (file2)
print()

print ((((file2>30) & (file2<70))))     #Takes & instead of and
print (~(((file2>30) & (file2<70))))    #Takes ~ instead of not (this matrix will be the opposite of the one above)
print ((((file2<=30) | (file2>=70))))   #Takes | instead of or (this matrix will be same as above and opposite of the first one)

[[  5.   6.   2.  33.]
 [  8.  88.   6.  76.]
 [ 23.  32.  55.  99.]
 [ 86. 123. 324. 511.]
 [777. 625. 318. 117.]]
[[  5   6   2  33]
 [  8  88   6  76]
 [ 23  32  55  99]
 [ 86 123  68  -1]
 [  9 113  62 117]]

[[False False False  True]
 [False False False False]
 [False  True  True False]
 [False False  True False]
 [False False  True False]]
[[ True  True  True False]
 [ True  True  True  True]
 [ True False False  True]
 [ True  True False  True]
 [ True  True False  True]]
[[ True  True  True False]
 [ True  True  True  True]
 [ True False False  True]
 [ True  True False  True]
 [ True  True False  True]]


In [18]:
#Self-defined function for mean/average
print (ar1)

def avg1(array):
    return np.sum(array)/array.size

def avg2(array):
    a = 0
    nr, nc = array.shape
    for i in range (nr):
        for j in range (nc):
            a += array[i, j]
    return a/(nr*nc)

print ("Average (Mean):", avg1(ar1))
print ("Mean (Average):", avg2(ar1))
print ("Actual value:", np.mean(ar1))

[[6 5 4]
 [7 8 9]]
Average (Mean): 6.5
Mean (Average): 6.5
Actual value: 6.5


In [19]:
#Self-defined function for median

def med(array):
    a = np.sort(array)
    nr, nc = array.shape    #Say 2, 3
    n = nr*nc
    if (nr%2==1 and nc%2==1):    #Odd number of elements
        return (a[int(nr/2), int((nc)/2)])
    elif (nr%2==1 and nc%2==0):    #Even number of elements (odd rows, even columns)
        return (a[int(nr/2), int(nc/2)] + a[int(nr/2), int((nc/2)-1)])/2
    elif (nr%2==0 and nc%2==1):    #Even number of elements (even rows, odd columns)
        return (a[int((nr-1)/2), nc-1] + a[int(nr/2), 0])/2
    elif (nr%2==0 and nc%2==0):    #Even number of elements (even rows, even columns)
        return (a[int(nr/2), int(nc/2)])

t1 = np.arange(0, 12).reshape(3, 4)
print (t1)
print ("Median:", med(t1))
print ("Actual value:", np.median(t1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Median: 5.5
Actual value: 5.5


In [20]:
#Self-defined function for variance

def variance(array):
    nr, nc = array.shape    #Say 2, 3
    n = nr*nc
    V = 0
    for i in range (nr):
        for j in range (nc):
            V += (array[i, j] - avg2(array))**2
    return V/n
    
t1 = np.arange(0, 12).reshape(3, 4)
print (t1)
print ("Variance:", variance(t1))
print ("Actual value:", np.var(t1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Variance: 11.916666666666666
Actual value: 11.916666666666666


In [21]:
#Self-defined function for standard deviation

def stddev(array):
    return (variance(array))**0.5

t1 = np.arange(0, 12).reshape(3, 4)
print (t1)
print ("Standard Deviation:", stddev(t1))
print ("Actual value:", np.std(t1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Standard Deviation: 3.452052529534663
Actual value: 3.452052529534663


In [22]:
#Different ways of accessing elements
q1 = np.arange(1, 31).reshape(6, 5)
q1
q1[2:4, 0:2]
q1[[0, 1, 2, 3], [1, 2, 3, 4]]
q1 [[0, 4, 5], 3:]    #Or 3:5

array([[ 4,  5],
       [24, 25],
       [29, 30]])

##Yet to explore:
#.random()
#.column_stack(), .row_stack()
#.diff()
#.r_[], .c_[]
#.view(), .multiply()
#.ix_()
#.savetxt()
#np.genfromtxt(arguments), np.loadtxt()
#bytearray(), ndarray()
#.newbyteorder(), .byteswap(), .tobytes()
#fromfile(), .tofile() 
#.flags.owndata
#.base
#slice()
#recfunctions
#Ellipsis
#numpy.lib.mixins
#Other NumPy objects